Rg palindromo exercise
RodoGalofre/Ruby-Exercises pull request #1
Opened 2019-07-17 21:03 UTC by RodoGalofre

2019-07-19 16:15 UTC, march23 reviewed
- this PR's does not have a description
- avoid mixin languages
- avoid unused code
- review a class definition

2019-07-19 16:15 UTC, march23 commented on Palindromo.rb
> +class PalindromoExcersise
is this a name for a class ? 
is this a name for a method?
what do you mean with piec?

let's review how a class should be defined and why

avoid mixin languages

2019-07-19 16:15 UTC, march23 commented on Palindromo.rb
> +                #puts " #{piec} es un palindromo"
avoid push commented lines on your code

2019-07-19 16:15 UTC, march23 commented on Palindromo.rb
> +obj = PalindromoExcersise.new
how this works ?
which params are you receiving?

let's review a class definition

2019-07-24 22:05 UTC, danielosorio83 requested changes

2019-07-24 22:05 UTC, danielosorio83 commented on Palindromo.rb
> +        if palindrome_valid.to_i > last_palindrome.to_i
podrias colocar esta condicion con un && en la condicion del if arriba y tiene el mismo efecto. no hay necesidad de colocar 2 if anidados si no hay mas nada

2019-07-25 15:49 UTC, danielosorio83 approved these changes

2019-07-25 15:49 UTC, merged