Rg fibonacci
RodoGalofre/Ruby-Exercises pull request #2
Opened 2019-07-17 21:04 UTC by RodoGalofre

2019-07-19 16:02 UTC, march23 reviewed
- review name conventions about method, vars, commits, branches etc
- this PR is not described so I am not sure , also it is not assigned

2019-07-19 16:02 UTC, march23 commented on Fibonacci_numbers_par.rb
> +a = 0
what is a, b and c? 

again a method should be name after what it does, a var should be name after what it means. 

lets review how we can achieve this result handling another ruby methods like `injection` or maybe something new with latest ruby version

2019-07-24 15:27 UTC, danielosorio83 requested changes

2019-07-24 15:27 UTC, danielosorio83 commented on Fibonacci_numbers_par.rb
> +  end
esto no devuelve lo q quieres

2019-07-24 15:27 UTC, danielosorio83 commented on Fibonacci_numbers_par.rb
> +def fibonacci_pars
este nombre no tiene como mucho sentido, colocale algo que sea mas correspondiente

2019-07-25 15:42 UTC, danielosorio83 requested changes

2019-07-25 15:42 UTC, danielosorio83 commented on Fibonacci_numbers_par-1-1.rb
> +
este archivo es necesario?

2019-07-25 15:43 UTC, RodoGalofre commented on Fibonacci_numbers_par-1-1.rb
> +
no

2019-07-25 15:44 UTC, RodoGalofre commented on Fibonacci_numbers_par-1-1.rb
> +
como hago para borrarlo desde la consola?

2019-07-25 15:48 UTC, danielosorio83 commented on Fibonacci_numbers_par-1-1.rb
> +
`rm nombre_del_archivo`
y luego lo comiteas

2019-07-25 15:49 UTC, RodoGalofre commented on Fibonacci_numbers_par-1-1.rb
> +
ya está hecho gracias

2019-07-25 15:55 UTC, danielosorio83 approved these changes

2019-07-25 15:55 UTC, merged