Rg multiples of3and5
RodoGalofre/Ruby-Exercises pull request #3
Opened 2019-07-17 21:06 UTC by RodoGalofre

2019-07-19 15:56 UTC, march23 reviewed
looks good about how it should work it out, please  review name conventions to methods, vars, see how your mixing print vs puts
and avoid mixing languages

- add description to your PR
- add reviewers

2019-07-24 15:29 UTC, danielosorio83 requested changes

2019-07-24 15:29 UTC, danielosorio83 commented on Multiples_Of_3_and_5.rb
> +    (1...1000).each {|i| multiples_of_three << i if i % number1 == 0 } # Rango de 1 a mil saca los multiplos de 3
aqui puedes aplicar el inject. mira a ver si lo puedes aplicar aqui

2019-07-24 15:29 UTC, danielosorio83 commented on Multiples_Of_3_and_5.rb
> +    (1...1000).each {|i| multiples_of_five << i if i % number2 == 0 } # Rango de 1 a mil saca los multiplos de 5
aqui puedes aplicar el inject. mira a ver si lo puedes aplicar aqui

2019-07-24 15:29 UTC, danielosorio83 commented on Multiples_Of_3_and_5.rb
> +    return multiples_of_three, multiples_of_five # se devuleven los arrays con los multiplos
cual es la idea de hacer un return asi? que te pide le ejercicio?

2019-07-24 15:44 UTC, RodoGalofre commented on Multiples_Of_3_and_5.rb
> +    (1...1000).each {|i| multiples_of_five << i if i % number2 == 0 } # Rango de 1 a mil saca los multiplos de 5
los multiplos de 3 y 5 hasta 1000

2019-07-24 15:46 UTC, danielosorio83 commented on Multiples_Of_3_and_5.rb
> +    (1...1000).each {|i| multiples_of_five << i if i % number2 == 0 } # Rango de 1 a mil saca los multiplos de 5
man.. revisa el ejercicio.. eso no es lo q estan pidiendo.
https://projecteuler.net/problem=1https://projecteuler.net/problem=1

2019-07-24 17:55 UTC, RodoGalofre commented
ya lo corregí no usé *inject* pero usé algo nuevo

2019-07-24 18:02 UTC, danielosorio83 requested changes

2019-07-24 18:02 UTC, danielosorio83 commented on Multiples_Of_3_and_5.rb
> +    (1...1000).each {|i|  i % number1 == 0 ? multiples_of_n << i :  (i % number2 == 0 ? multiples_of_n << i : nil )}
buena idea... pero revisa en el ruby-style-guide que dice respecto a los condicionales de una linea con doble condicional

2019-07-24 18:04 UTC, RodoGalofre commented on Multiples_Of_3_and_5.rb
> +    (1...1000).each {|i|  i % number1 == 0 ? multiples_of_n << i :  (i % number2 == 0 ? multiples_of_n << i : nil )}
ok bien

2019-07-24 18:45 UTC, danielosorio83 requested changes

2019-07-24 18:45 UTC, danielosorio83 commented on Multiples_Of_3_and_5.rb
> +    (1...1000).each { |i|
mucho mejor... para multilineas no se usa `{...}` sino
```
do |param|
...
end
```

2019-07-24 18:45 UTC, danielosorio83 commented on Multiples_Of_3_and_5.rb
> +    if i % number1 == 0
tienes problemas de identacion todavia? averigua por identacion en cascada...
siempre que se abre un metodo se identa uno hacia la derecha

2019-07-24 19:40 UTC, danielosorio83 approved these changes

2019-07-24 19:40 UTC, merged